import { AIReport, Detection } from '../types';
import { loggingService } from './loggingService';
import { LogType } from '../types';

export class GroqService {
  static async validateWithGroq(geminiReport: AIReport, vtResults: any, detections: Detection[]): Promise<AIReport> {
    await loggingService.log(LogType.EXPLANATION, "GroqValidationNode", { 
      action: "validatingAI", 
      status: "In Progress"
    });

    const systemPrompt = `You are the final AI security arbiter acting as a two-step verification module for an Autonomous SIEM system.
You will be provided with:
1) An initial threat analysis report generated by Gemini.
2) Structured Threat Intelligence data from VirusTotal.
3) The core detection summaries.

Your objective is to combine these insights, rigorously validate the initial report against the hard VirusTotal data, and produce the FINAL authoritative JSON report.
If VirusTotal flags an entity as "malicious" with a high count (e.g. > 3), ensure the risk level is set to HIGH.

Format your output STRICTLY as a JSON object matching this schema:
{
  "summary": "String",
  "attack_type": "String",
  "mitre_id": "String (e.g. T1110)",
  "remediation_code": "String (bash/iptables code snippet)",
  "risk": "LOW | MEDIUM | HIGH",
  "explanation": "String (Explain how the Gemini context and VT data were combined to reach this conclusion)",
  "recommended_action": "String"
}`;

    const userPrompt = `
INITIAL GEMINI REPORT:
${JSON.stringify(geminiReport, null, 2)}

VIRUSTOTAL FINDINGS:
${JSON.stringify(vtResults, null, 2)}

DETECTION CONTEXT:
${JSON.stringify(detections.map(d => d.type), null, 2)}
`;

    try {
      const response = await fetch('/api/proxy/groq', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama3-70b-8192',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          response_format: { type: "json_object" },
          temperature: 0.1 // Keep it analytical and deterministic
        })
      });

      if (response.ok) {
        const data = await response.json();
        const content = data.choices[0]?.message?.content;
        const finalizedReport = JSON.parse(content) as AIReport;
        
        await loggingService.log(LogType.EXPLANATION, "GroqValidationNode", { result: finalizedReport });
        return finalizedReport;
      } else {
        console.error("Groq API Error:", response.status, await response.text());
        return geminiReport;
      }
    } catch (err) {
      console.error("Failed to query Groq:", err);
      return geminiReport;
    }
  }
}
